<MyGridLayout>

    name:name
    download:download

    GridLayout:
        cols: 1
        size: root.width, root.height

        GridLayout:
            cols: 2

            Label:
                id: name
                text: "Download"
            TextInput:
                id: download
                multiline: False
        Button:
            text: "Enter"
            font_size: 21
            on_press: root.press()